# docker-compose up -d
# docker-compose down

version: "3.6"
networks:
  localdev:
    name: localdev

services:
  pymage.io:
    privileged: true
    entrypoint: ["dotnet","API.dll"]    
    build:
      context: .
      dockerfile: src/API/Dockerfile
    image: pymage_io:latest
    container_name: pymage.io
    networks:
      - localdev
